// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalTourismSystem.Data;

#nullable disable

namespace RentalTourismSystem.Migrations
{
    [DbContext(typeof(RentalTourismContext))]
    partial class RentalTourismContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Agencias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CNPJ = "12.345.678/0001-90",
                            Cidade = "João Pessoa - PB",
                            Email = "central@rentaltourism.com.br",
                            Endereco = "Rua Principal, 123 - Centro",
                            Nome = "Agência Central",
                            Telefone = "(83) 3221-1234"
                        });
                });

            modelBuilder.Entity("RentalTourismSystem.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AgenciaId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("[Cpf] IS NOT NULL");

                    b.HasIndex("FuncionarioId")
                        .IsUnique()
                        .HasFilter("[FuncionarioId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CEP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CNH")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CNHPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("CategoriaCNH")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Profissao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ValidadeCNH")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioUpload")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataUpload");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("TipoDocumento");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenciaId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.ItemManutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPeca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Fornecedor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ManutencaoVeiculoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ManutencaoVeiculoId");

                    b.ToTable("ItensManutencao");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Locacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenciaId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDevolucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDevolucaoReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRetirada")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("QuilometragemDevolucao")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Locacoes");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.ManutencaoVeiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Custo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("CustoMaoObra")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("CustoPecas")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DataAgendada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int?>("GarantiaDias")
                        .HasColumnType("int");

                    b.Property<string>("NotaFiscal")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Oficina")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Preventiva")
                        .HasColumnType("bit");

                    b.Property<int?>("ProximaQuilometragem")
                        .HasColumnType("int");

                    b.Property<int>("QuilometragemAtual")
                        .HasColumnType("int");

                    b.Property<int>("StatusManutencaoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoManutencaoId")
                        .HasColumnType("int");

                    b.Property<bool>("Urgente")
                        .HasColumnType("bit");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataAgendada");

                    b.HasIndex("DataConclusao");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("StatusManutencaoId");

                    b.HasIndex("TipoManutencaoId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("ManutencoesVeiculos");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLeitura")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<string>("LinkAcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocacaoId")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<int?>("ReservaId")
                        .HasColumnType("int");

                    b.Property<string>("TextoLinkAcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("Lida");

                    b.HasIndex("LocacaoId");

                    b.HasIndex("ReservaId");

                    b.HasIndex("Tipo");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.PacoteViagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UnidadeTempo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PacotesViagens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "3 dias e 2 noites na Praia do Forte com café da manhã incluso",
                            Destino = "Praia do Forte - BA",
                            Duracao = 3,
                            Nome = "Pacote Praia do Forte",
                            Preco = 850.00m,
                            UnidadeTempo = "dias"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 20, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "5 dias na Serra da Mantiqueira com todas as refeições",
                            Destino = "Serra da Mantiqueira - MG",
                            Duracao = 5,
                            Nome = "Pacote Serra da Mantiqueira",
                            Preco = 1200.00m,
                            UnidadeTempo = "dias"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 2, 1, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Emocionante passeio de buggy pelas dunas de Natal com parada para banho de lagoa",
                            Destino = "Genipabu - RN",
                            Duracao = 4,
                            Nome = "Passeio de Buggy nas Dunas",
                            Preco = 120.00m,
                            UnidadeTempo = "horas"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 2, 10, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Mergulho com cilindro nos recifes de coral de Porto de Galinhas, equipamentos inclusos",
                            Destino = "Porto de Galinhas - PE",
                            Duracao = 3,
                            Nome = "Mergulho em Recife de Coral",
                            Preco = 180.00m,
                            UnidadeTempo = "horas"
                        });
                });

            modelBuilder.Entity("RentalTourismSystem.Models.ReservaViagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataViagem")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PacoteViagemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("StatusReservaViagemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PacoteViagemId");

                    b.HasIndex("StatusReservaViagemId");

                    b.ToTable("ReservasViagens");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.ServicoAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ReservaViagemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservaViagemId");

                    b.ToTable("ServicosAdicionais");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.StatusCarro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("StatusCarros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Disponível"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Alugado"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Manutenção"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Indisponível"
                        });
                });

            modelBuilder.Entity("RentalTourismSystem.Models.StatusManutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("StatusManutencoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Manutenção agendada, aguardando início",
                            Status = "Agendada"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Manutenção em execução",
                            Status = "Em Andamento"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Manutenção concluída com sucesso",
                            Status = "Concluída"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Manutenção cancelada",
                            Status = "Cancelada"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Aguardando aprovação de orçamento",
                            Status = "Pendente Aprovação"
                        });
                });

            modelBuilder.Entity("RentalTourismSystem.Models.StatusReservaViagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("StatusReservaViagens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Confirmada"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Cancelada"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Realizada"
                        });
                });

            modelBuilder.Entity("RentalTourismSystem.Models.TipoManutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposManutencao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Troca de óleo do motor e filtro",
                            Nome = "Troca de Óleo"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "Revisão programada conforme manual",
                            Nome = "Revisão Periódica"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "Substituição de pneus",
                            Nome = "Troca de Pneus"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Descricao = "Serviço de alinhamento e balanceamento",
                            Nome = "Alinhamento e Balanceamento"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Descricao = "Manutenção do sistema de freios",
                            Nome = "Freios"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Descricao = "Manutenção do sistema de suspensão",
                            Nome = "Suspensão"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Descricao = "Manutenção do sistema de climatização",
                            Nome = "Ar Condicionado"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Descricao = "Troca ou manutenção da bateria",
                            Nome = "Bateria"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Descricao = "Reparos no sistema elétrico",
                            Nome = "Sistema Elétrico"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Descricao = "Reparos no motor",
                            Nome = "Motor"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            Descricao = "Manutenção do sistema de transmissão",
                            Nome = "Câmbio"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            Descricao = "Reparos de lataria e funilaria",
                            Nome = "Funilaria"
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            Descricao = "Serviços de pintura",
                            Nome = "Pintura"
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            Descricao = "Troca ou reparo de vidros",
                            Nome = "Vidros"
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            Descricao = "Limpeza interna e externa detalhada",
                            Nome = "Limpeza Completa"
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            Descricao = "Inspeção veicular obrigatória",
                            Nome = "Inspeção Veicular"
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            Descricao = "Outras manutenções não especificadas",
                            Nome = "Outros"
                        });
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenciaId")
                        .HasColumnType("int");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Cambio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Combustivel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("int");

                    b.Property<int>("StatusCarroId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorDiaria")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ValorMercado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.HasIndex("StatusCarroId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RentalTourismSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RentalTourismSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalTourismSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RentalTourismSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentalTourismSystem.Models.ApplicationUser", b =>
                {
                    b.HasOne("RentalTourismSystem.Models.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RentalTourismSystem.Models.Funcionario", "Funcionario")
                        .WithOne()
                        .HasForeignKey("RentalTourismSystem.Models.ApplicationUser", "FuncionarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agencia");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Documento", b =>
                {
                    b.HasOne("RentalTourismSystem.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RentalTourismSystem.Models.Cliente", "Cliente")
                        .WithMany("Documentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RentalTourismSystem.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RentalTourismSystem.Models.Veiculo", "Veiculo")
                        .WithMany("Documentos")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ApplicationUser");

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Funcionario", b =>
                {
                    b.HasOne("RentalTourismSystem.Models.Agencia", "Agencia")
                        .WithMany("Funcionarios")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.ItemManutencao", b =>
                {
                    b.HasOne("RentalTourismSystem.Models.ManutencaoVeiculo", "ManutencaoVeiculo")
                        .WithMany("Itens")
                        .HasForeignKey("ManutencaoVeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManutencaoVeiculo");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Locacao", b =>
                {
                    b.HasOne("RentalTourismSystem.Models.Agencia", "Agencia")
                        .WithMany("Locacoes")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalTourismSystem.Models.Cliente", "Cliente")
                        .WithMany("Locacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalTourismSystem.Models.Funcionario", "Funcionario")
                        .WithMany("Locacoes")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalTourismSystem.Models.Veiculo", "Veiculo")
                        .WithMany("Locacoes")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.ManutencaoVeiculo", b =>
                {
                    b.HasOne("RentalTourismSystem.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RentalTourismSystem.Models.StatusManutencao", "StatusManutencao")
                        .WithMany("Manutencoes")
                        .HasForeignKey("StatusManutencaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalTourismSystem.Models.TipoManutencao", "TipoManutencao")
                        .WithMany("Manutencoes")
                        .HasForeignKey("TipoManutencaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalTourismSystem.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("StatusManutencao");

                    b.Navigation("TipoManutencao");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Notificacao", b =>
                {
                    b.HasOne("RentalTourismSystem.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RentalTourismSystem.Models.Locacao", "Locacao")
                        .WithMany()
                        .HasForeignKey("LocacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RentalTourismSystem.Models.ReservaViagem", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RentalTourismSystem.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cliente");

                    b.Navigation("Locacao");

                    b.Navigation("Reserva");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.ReservaViagem", b =>
                {
                    b.HasOne("RentalTourismSystem.Models.Cliente", "Cliente")
                        .WithMany("ReservasViagens")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalTourismSystem.Models.PacoteViagem", "PacoteViagem")
                        .WithMany("ReservasViagens")
                        .HasForeignKey("PacoteViagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalTourismSystem.Models.StatusReservaViagem", "StatusReservaViagem")
                        .WithMany("ReservasViagens")
                        .HasForeignKey("StatusReservaViagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("PacoteViagem");

                    b.Navigation("StatusReservaViagem");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.ServicoAdicional", b =>
                {
                    b.HasOne("RentalTourismSystem.Models.ReservaViagem", "ReservaViagem")
                        .WithMany("ServicosAdicionais")
                        .HasForeignKey("ReservaViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservaViagem");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Veiculo", b =>
                {
                    b.HasOne("RentalTourismSystem.Models.Agencia", "Agencia")
                        .WithMany("Veiculos")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalTourismSystem.Models.StatusCarro", "StatusCarro")
                        .WithMany("Veiculos")
                        .HasForeignKey("StatusCarroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("StatusCarro");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Agencia", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("Locacoes");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Cliente", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Locacoes");

                    b.Navigation("ReservasViagens");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Funcionario", b =>
                {
                    b.Navigation("Locacoes");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.ManutencaoVeiculo", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.PacoteViagem", b =>
                {
                    b.Navigation("ReservasViagens");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.ReservaViagem", b =>
                {
                    b.Navigation("ServicosAdicionais");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.StatusCarro", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.StatusManutencao", b =>
                {
                    b.Navigation("Manutencoes");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.StatusReservaViagem", b =>
                {
                    b.Navigation("ReservasViagens");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.TipoManutencao", b =>
                {
                    b.Navigation("Manutencoes");
                });

            modelBuilder.Entity("RentalTourismSystem.Models.Veiculo", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Locacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
